### ISSUE TITLE
exit with getting ID of event

### ISSUE THREAD

**Issue by asheshambasta** [phensley/docker-dns#21]
Log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "./dockerdns", line 127, in run
    cid = evt['id']
KeyError: 'id'
<Greenlet at 0x7f10b530fb90: <bound method DockerMonitor.run of <__main__.DockerMonitor object at 0x7f10b506e710>>> failed with KeyError
```

docker version:
```Docker version 1.12.1, build 23cf638```

**Comment by phensley** [comment]
I'm not able to reproduce this on the latest version. The `id` key is present in the event stream. I added a fallback to use the uppercase key if lowercase is not present.
```
2019-04-28T15:31:01.495885 [dockerdns] {u'status': u'create', 
 u'timeNano': 1556465461495117629, u'from': u'ubuntu', 
 u'Actor': {u'Attributes': {u'image': u'ubuntu', u'name': u'bar'}, 
 u'ID': u'91c2b7d714778eef9e44e50381c1b1579f25f6f157cdb14701eea3bfc12bba9c'}, 
 u'time': 1556465461, u'Action': u'create', u'scope': u'local', 
 u'Type': u'container',
 u'id': u'91c2b7d714778eef9e44e50381c1b1579f25f6f157cdb14701eea3bfc12bba9c'}
```

**Comment by asheshambasta** [comment]
Thanks, unfortunately, I no longer have the context on this to be able to provide you with any kind of repro.
